# Generated by Django 4.2.1 on 2023-05-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateSwipe_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='iduser',
            new_name='idUser',
        ),
    ]
