# Generated by Django 4.2.1 on 2023-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateSwipe_APP', '0002_rename_iduser_message_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(null=True, related_name='liked_properties', to='RealEstateSwipe_APP.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passed',
            field=models.ManyToManyField(null=True, related_name='disliked_properties', to='RealEstateSwipe_APP.property'),
        ),
    ]
