# Generated by Django 4.2.1 on 2023-05-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateSwipe_APP', '0003_alter_user_liked_alter_user_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idConversation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RealEstateSwipe_APP.conversation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_properties', to='RealEstateSwipe_APP.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passed',
            field=models.ManyToManyField(blank=True, related_name='disliked_properties', to='RealEstateSwipe_APP.property'),
        ),
    ]
